// <auto-generated />
using System;
using Day0Lab.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day0Lab.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251015053206_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Day0Lab.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DonGiaMua")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("DonGiaMua");

                    b.Property<int?>("HoaDonID")
                        .HasColumnType("int")
                        .HasColumnName("HoaDonID");

                    b.Property<int?>("SanPhamID")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamID");

                    b.Property<int?>("SoLuongMua")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongMua");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("ThanhTien");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TrangThai");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonID");

                    b.HasIndex("SanPhamID");

                    b.ToTable("CT_HOA_DON");
                });

            modelBuilder.Entity("Day0Lab.Models.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("DienThoai");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("HoTenKhachHang")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("HoTenKhachHang");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaHoaDon");

                    b.Property<int?>("MaKhaHang")
                        .HasColumnType("int")
                        .HasColumnName("MaKhaHang");

                    b.Property<DateTime?>("NgayHoaDon")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayHoaDon");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayNhan");

                    b.Property<int?>("QuanTriId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongTriGia")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("TongTriGia");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TrangThai");

                    b.HasKey("Id");

                    b.HasIndex("MaKhaHang");

                    b.HasIndex("QuanTriId");

                    b.ToTable("HOA_DON");
                });

            modelBuilder.Entity("Day0Lab.Models.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("DienThoai");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("HoTenKhachHang")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("HoTenKhachHang");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaKhachHang");

                    b.Property<string>("MaKhau")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MaKhau");

                    b.Property<DateTime?>("NgayDangKy")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayDangKy");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TrangThai");

                    b.HasKey("Id");

                    b.ToTable("KHACH_HANG");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiaChi = "Hà Nội",
                            DienThoai = "0901234567",
                            Email = "nguyenvana@email.com",
                            HoTenKhachHang = "Nguyễn Văn A",
                            MaKhachHang = "KH001",
                            NgayDangKy = new DateTime(2025, 10, 15, 12, 32, 6, 352, DateTimeKind.Local).AddTicks(5079),
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("Day0Lab.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaLoai");

                    b.Property<string>("TenLoai")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenLoai");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TrangThai");

                    b.HasKey("Id");

                    b.ToTable("LOAI_SAN_PHAM");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaLoai = "LSP001",
                            TenLoai = "Điện thoại",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 2,
                            MaLoai = "LSP002",
                            TenLoai = "Laptop",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 3,
                            MaLoai = "LSP003",
                            TenLoai = "Phụ kiện",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("Day0Lab.Models.QuanTri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MatKhau");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TaiKhoan");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TrangThai");

                    b.HasKey("Id");

                    b.ToTable("QUAN_TRI");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MatKhau = "123456",
                            TaiKhoan = "admin",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("Day0Lab.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("DonGia");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("HinhAnh");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("int")
                        .HasColumnName("MaLoai");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaSanPham");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenSanPham");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TrangThai");

                    b.HasKey("Id");

                    b.HasIndex("MaLoai");

                    b.ToTable("SAN_PHAM");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DonGia = 29990000m,
                            MaLoai = 1,
                            MaSanPham = "SP001",
                            SoLuong = 50,
                            TenSanPham = "iPhone 15 Pro",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 2,
                            DonGia = 22990000m,
                            MaLoai = 1,
                            MaSanPham = "SP002",
                            SoLuong = 40,
                            TenSanPham = "Samsung Galaxy S24",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 3,
                            DonGia = 45990000m,
                            MaLoai = 2,
                            MaSanPham = "SP003",
                            SoLuong = 20,
                            TenSanPham = "MacBook Pro M3",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("Day0Lab.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("Day0Lab.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Day0Lab.Models.SanPham", "SanPham")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("SanPhamID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Day0Lab.Models.HoaDon", b =>
                {
                    b.HasOne("Day0Lab.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKhaHang")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Day0Lab.Models.QuanTri", "QuanTri")
                        .WithMany("HoaDons")
                        .HasForeignKey("QuanTriId");

                    b.Navigation("KhachHang");

                    b.Navigation("QuanTri");
                });

            modelBuilder.Entity("Day0Lab.Models.SanPham", b =>
                {
                    b.HasOne("Day0Lab.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("Day0Lab.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("Day0Lab.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Day0Lab.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("Day0Lab.Models.QuanTri", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Day0Lab.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
