// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NguyenDucThach_231230898_de02.Entities;

#nullable disable

namespace NguyenDucThach_231230898_de02.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251024040044_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NguyenDucThach_231230898_de02.Models.NguyenDucThachCatalog", b =>
                {
                    b.Property<int>("hvtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hvtId"));

                    b.Property<bool>("hvtCateActive")
                        .HasColumnType("bit");

                    b.Property<string>("hvtCateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("hvtCatePrice")
                        .HasColumnType("float");

                    b.Property<int>("hvtCateQty")
                        .HasColumnType("int");

                    b.Property<string>("hvtPicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("hvtId");

                    b.ToTable("NguyenDucThachCatalog");
                });
#pragma warning restore 612, 618
        }
    }
}
