// <auto-generated />
using BTTrenlop17_10.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTTrenlop17_10.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BTTrenlop17_10.Models.TVCLoaiSanPham", b =>
                {
                    b.Property<long>("PVCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PVCId"));

                    b.Property<string>("TVCMaLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TVCTenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TVCTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("PVCId");

                    b.HasIndex("TVCMaLoai");

                    b.ToTable("TVCLoaiSanPham");
                });

            modelBuilder.Entity("BTTrenlop17_10.Models.TVCSanPham", b =>
                {
                    b.Property<long>("TVCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TVCId"));

                    b.Property<string>("TVCDonGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TVCHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TVCLoaiSanPhamId")
                        .HasColumnType("bigint");

                    b.Property<string>("TVCMasanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TVCSoLuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TVCTenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TVCId");

                    b.HasIndex("TVCLoaiSanPhamId");

                    b.ToTable("TVCSanPham");
                });

            modelBuilder.Entity("BTTrenlop17_10.Models.TVCSanPham", b =>
                {
                    b.HasOne("BTTrenlop17_10.Models.TVCLoaiSanPham", "TVCLoaiSanPham")
                        .WithMany("TVCSanPhams")
                        .HasForeignKey("TVCLoaiSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TVCLoaiSanPham");
                });

            modelBuilder.Entity("BTTrenlop17_10.Models.TVCLoaiSanPham", b =>
                {
                    b.Navigation("TVCSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
